events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        location / {
            proxy_pass http://frontend:80;
        }
        
        location /generate {
            proxy_pass http://backend:5000/generate;
            proxy_set_header Host $host;
            proxy_set_header Content-Type $content_type;
        }
    }
}